### ISSUE TITLE
SQL Database and other functions

### ISSUE THREAD

**Issue by japnimedev** [VottonDev/nyanpasu.tv#1]
Could you upload the sql format of this :)

**Comment by VottonDev** [comment]
It has been uploaded now: https://github.com/VottonDev/nyanpasu.tv/blob/master/nyanpasu.sql

**Comment by fujikawachiai** [comment]
![image](https://user-images.githubusercontent.com/43559958/52928364-536a1a80-337a-11e9-8a3c-b8275b0866e7.png)
can you gimme solution for this?
